vendor: robin.io
name: robin-cnp
version: v5.4.1
website_url: https://robin.io/
repo_url: https://github.com/Robinsystems/robin
documentation_url: https://docs.robin.io/platform/latest/
product_logo_url: https://www.robin.io/wp-content/uploads/2019/10/cropped-robin-new-logo-white-bg-1024x217-1.png
type: Distribution
description: 'ROBIN Platform, the industry’s first hyper-converged Kubernetes platform for big data, databases, AI/ML and 5G workloads'

