vendor: Cisco Systems
name: Intersight Kubernetes Service
version: 1.0.5
website_url: http://www.cisco.com/go/containers
documentation_url: <Not Available>
product_logo_url: <Not Available>
type: distribution
description: Intersight Kubernetes Service provides a platform for deployment and lifecycle management of Kubernetes clusters.
