vendor: OpenNebula Systems
name: OpenNebula - Kubernetes Appliance
version: v1.18
website_url: https://marketplace.opennebula.io/appliance/547ecdff-f392-43b9-abc9-5f10a9fa7aff
documentation_url: https://docs.opennebula.io/appliances/service/kubernetes.html
product_logo_url: https://opennebula.io/logo-blue.svg
type: Installer
description: Virtual Appliance for KVM with preinstalled Kubernetes service available from OpenNebula's Public Marketplace. The Appliance deploys a single Kubernetes master node. It can be customized with contextualization parameters to support multi-node clusters.
