vendor: Nutanix
name: Karbon
version: v2.2.2
documentation_url: https://portal.nutanix.com/page/documents/details/?targetId=Release-Notes-Karbon-v2_2_2%3ARelease-Notes-Karbon-v2_2_2
website_url: https://www.nutanix.com
product_logo_url: https://www.nutanix.com/wp-content/uploads/2017/11/nutanix.png
type: hosted
description: Managed Kubernetes offering by Nutanix
