vendor: VMware
name: VMware Tanzu Community Edition
version: 0.12.0
website_url: https://tanzucommunityedition.io
repo_url: https://github.com/vmware-tanzu/community-edition
documentation_url: https://tanzucommunityedition.io/docs/latest
product_logo_url: https://raw.githubusercontent.com/vmware-tanzu/community-edition/main/docs/images/logos/TCE%20Logo%20SVG.svg
type: distribution
description: 'VMware Tanzu Community Edition is a full-featured, easy-to-manage Kubernetes platform for practitioners and learners.'
