PRODUCT.yaml:
vendor: Replicated, Inc.
name: kURL
version: v2022.05.02-0
website_url: https://kurl.sh
repo_url: https://github.com/replicatedhq/kurl
documentation_url: https://kurl.sh/docs
product_logo_url: https://camo.githubusercontent.com/4fdafd9fc9e5f8e564d9697acf74f7e04dc180ef/68747470733a2f2f6b75726c2e73682f6b75726c5f6c6f676f4032782e706e67
type: distribution
description: 'A Kubernetes distro creator ideal for delivering K8s-based apps to on-prem or airgapped environments.'
