vendor: Inspur
name: InCloud OS
version: v6
website_url: https://www.inspur.com/lcjtww/2527835/2527836/2527854/index.html
documentation_url: https://www.inspur.com/eportal/fileDir/defaultCurSite/resource/cms/2021/07/2021072711401812874.pdf
product_logo_url: https://raw.githubusercontent.com/lilongfeng0902/k8s-conformance/inspur-lilf-branch/v1.23/inspur-incloudos-amd64/incloudoslogo.svg
type: hosted 
description: InCloud OS, offering full lifecycle management services, is an application-centric platform which provides a High-available managed environment to simplify the CI/CD, Deployment, Container Orchestration ，ServiceMesh，scheduling and scaling of containerized applications.
