vendor: LStack Hybrid Cloud
name: Launcher Tech LStack Container Service for Kubernetes
version: v100r001c02b013
website_url: https://www.lstack.com
documentation_url: https://console.lstack.com/document
product_logo_url: https://lstack-lcs.oss-cn-beijing.aliyuncs.com/lstack-logo.svg
type: hosted
description: 'LStack Cloud Service (lcs) is a high-performance, high-reliability service through which enterprises can manage containerized applications. LCS supports native Kubernetes applications and tools, allowing you to easily set up a container runtime environment on the cloud.'