  
vendor: KBSYS Inc.
name: Bizmicro-Portal
version: 0.9                                
website_url: http://portal.kb-sys.co.kr
documentation_url: http://portal.kb-sys.co.kr/files/BizMicro_Eng.pdf
product_logo_url: http://portal.kb-sys.co.kr/files/bizlogo_black.svg
type: hosted platform
description: Bizmicro is a practical, use-oriented call support platform for customer consultations.
