vendor: Google
name: Google Kubernetes Engine
version: 1.21.1-gke.2200
website_url: https://cloud.google.com/kubernetes-engine/
documentation_url: https://cloud.google.com/kubernetes-engine/docs/
product_logo_url: https://www.gstatic.com/devrel-devsite/prod/v3069b08f6c9d146fa6a9c7f184b2836998ab5f12cefec1342a7bf6dca024aa94/cloud/images/cloud-logo.svg
type: hosted
description: 'GKE is an enterprise-grade platform for containerized applications, including stateful and stateless, AI and ML, Linux and Windows, complex and simple web apps, API, and backend services.'
