vendor: Canonical Ltd
name: Charmed Distribution of Kubernetes
version: v1.21.0
website_url: https://www.ubuntu.com/kubernetes
repo_url: https://github.com/charmed-kubernetes/bundle
documentation_url: https://ubuntu.com/kubernetes/docs
product_logo_url: https://landscape.cncf.io/logos/canonical-charmed-distribution-of-kubernetes.svg
type: distribution
description: Deploy, scale and upgrade Kubernetes clusters across multiple physical or virtual machines with Charmed Kubernetes.
