vendor: Beijing Baolande Software Corporation(北京宝兰德软件股份有限公司)
name: CloudLink-CMP
version: v4.2
website_url: https://www.bessystem.com/product/31f9842c24e5441394b85bfdc7a9d7df/info
documentation_url: https://www.bessystem.com/product/31f9842c24e5441394b85bfdc7a9d7df/info
product_logo_url: https://github.com/zhannk/k8s-conformance/tree/master/v1.24/cloudlink-cmp/CloudLink-logo.svg
type: hosted
description: CloudLink CMP is a kubernetes enabled enterprise-ready PaaS solution, consists of features like CICD、multi-tenant、rich micro-services and components support, integrated with an easy-to-use operation/maintenance interface.
