vendor: Inspur
name: ICKS
version: v2.3
website_url: https://www.inspur.com/lcjtww/2527835/2527836/2527854/index.html
documentation_url: https://www.inspur.com/eportal/fileDir/defaultCurSite/resource/cms/2021/07/2021072711401812874.pdf
product_logo_url: https://upload.wikimedia.org/wikipedia/en/7/73/Inspur_logo.svg
type: hosted 
description: ICKS, offering full lifecycle management services, is an application-centric platform which provides a High-available managed environment to simplify the development, CI/CD, deployment, scheduling and scaling of containerized applications. 
