vendor: OpenNebula Systems
name: OpenNebula - Kubernetes Appliance
version: v1.23
website_url: https://marketplace.opennebula.io/appliance/b5033eba-cd31-487e-892a-035cd70441ef
documentation_url: https://docs.opennebula.io/appliances/service/kubernetes_service.html
product_logo_url: https://opennebula.io/logo-blue.svg
type: Installer
description: Virtual Appliance for KVM with preinstalled Kubernetes service available from OpenNebula's Public Marketplace. The Appliance deploys a multi-master and multi-node Kubernetes cluster.
