vendor: Amazon Web Services
name: Amazon Elastic Kubernetes Service Distro (Amazon EKS-D)
version: v1.18.9
website_url: https://aws.amazon.com/eks/eks-distro
repo_url: https://github.com/aws/eks-distro
documentation_url: https://distro.eks.amazonaws.com/
product_logo_url: https://a0.awsstatic.com/libra-css/images/logos/aws_logo_smile_1200x630.png
type: distribution
description: Amazon Elastic Kubernetes Service Distro (Amazon EKS-D) is a Kubernetes distribution based on and used by Amazon Elastic Kubernetes Service (EKS) to create reliable and secure Kubernetes clusters.
