vendor: JD Cloud
name: JCS for Kubernetes
version: v1.18.8
website_url: https://www.jdcloud.com/en/products/jcs-for-kubernetes
documentation_url: https://docs.jdcloud.com/en/jcs-for-kubernetes/product-overview
product_logo_url: https://bj-jcs-agent-linux.s3.cn-north-1.jdcloud-oss.com/jdcloud.svg
type: hosted
description: By adopting fully-hosted management node, JCS for Kubernetes offers simple, easy-to-use, high-reliable and powerful container management service to users. Compatible with Kubernetes API, integrating network, storage and other JD Cloud plug-ins.