vendor: Microsoft
name: AKS Engine for Azure Stack
version: v0.58.0
website_url: https://github.com/Azure/aks-engine
documentation_url: https://github.com/Azure/aks-engine/blob/master/docs/topics/azure-stack.md
product_logo_url: https://landscape.cncf.io/logos/azure-aks-engine.svg
type: hosted platform
description: AKS Engine provides convenient tooling to quickly bootstrap Kubernetes clusters on Azure Stack. By leveraging ARM (Azure Resource Manager), AKS Engine helps create, destroy and maintain clusters provisioned with basic IaaS resources in Azure Stack.