vendor: German Edge Cloud GmbH
name: iMKE
version: v1.18.13
website_url: https://gec.io/cloud-automation/gec-kubernetes-service/
documentation_url: https://docs.imke.cloud
product_logo_url: https://raw.githubusercontent.com/cedi/gec-logo/master/german-edge-cloud.svg
type: hosted platform
description: 'iMKE. The first choice for Industrial and Finance clients Kubernetes.'
