PRODUCT.yaml:
vendor: Replicated, Inc.
name: kURL
version: v2022.05.02-0
website_url: https://kurl.sh
repo_url: https://github.com/replicatedhq/kurl
documentation_url: https://kurl.sh/docs
product_logo_url: https://raw.githubusercontent.com/replicatedhq/community/main/assets/logos/kurl.svg
type: distribution
description: 'A Kubernetes distro creator ideal for delivering K8s-based apps to on-prem or airgapped environments.'
