vendor: Cisco Systems
name: Intersight Kubernetes Service
version: 1.1.1
website_url: http://www.cisco.com/go/containers
documentation_url: https://intersight.com/help/saas/resources/intersight_kubernetes_service_user_guide
product_logo_url:
type: distribution
description: Intersight Kubernetes Service provides a platform for deployment and lifecycle management of Kubernetes clusters.
