
vendor: Fujitsu Cloud Technologies Limited
name: NIFCLOUD Hatoba
version: v1.17.11
website_url: https://pfs.nifcloud.com/service/hatoba.htm
documentation_url: https://pfs.nifcloud.com/spec/hatoba/
product_logo_url: https://pfs.nifcloud.com/service/images/hatoba_logo.svg
type: hosted
description: 'NIFCLOUD Hatoba is a managed Kubernetes as a Service to deploy enterprise container applications and operate them simply and useful on NIFCLOUD.'
