vendor: Huawei
name: HUAWEI CLOUD Cloud Container Engine
version: v1.21.4-r0-CCE21.11.1.B001
website_url: http://www.huaweicloud.com/product/cce.html
documentation_url: http://support.huaweicloud.com/cce/index.html
product_logo_url: https://www-file.huawei.com/-/media/corporate/images/home/logo/huawei_logo.png
type: hosted
description: 'Cloud Container Engine (CCE) is a high-performance, high-reliability service through which enterprises can manage containerized applications. CCE supports native Kubernetes applications and tools, allowing you to easily set up a container runtime environment on the cloud.'
