vendor: Replicated, Inc.
name: kURL
version: v2021.08.20-0
website_url: https://kurl.sh
repo_url: https://github.com/replicatedhq/kurl
documentation_url: https://kurl.sh/docs
product_logo_url: https://raw.githubusercontent.com/replicatedhq/community/main/assets/logos/kurl.svg
type: distribution
description: "Kubernetes URL (kURL) is a framework for creating custom Kubernetes distributions. These distros can then be shared as URLs (to install via curl and bash) or as downloadable packages (to install in airgapped environments)."
