vendor:  Morpheus Data, LLC
name: Morpheus
version: v1.20.0
website_url: https://www.morpheusdata.com/
repo_url:
documentation_url: https://docs.morpheusdata.com/en/5.3.1/integration_guides/Containers/kubernetes.html?highlight=kubernetes
product_logo_url: https://morpheusdata.com/wp-content/uploads/2020/04/morpheus-logo-v2.svg
type: distribution
description: 'Morpheus is a hybrid cloud orchestration tool'
